version: '3.7'

services:
  pgsql_db:
    image: postgres:latest
    container_name: postgersql_db
    restart: always
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123456"
    ports:
      - 5432:5432